version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: mhart/alpine-node

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm i pnpm -g

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: pnpm i --frozen-shrinkwrap

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


      - run: pnpm test
