version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
        key: pkg-cache-{{ checksum "package-lock.json" }}

      - run: npm ci

      - save_cache:
        paths:
          - ./node_modules
        key: pkg-cache-{{ checksum "package-lock.json" }}


      - run: npm test
